"""Turns a training-example.schema.json record into the prompt/target text
pair a model is trained and evaluated on. Shared by train.py and evaluate.py
so training and inference never drift apart.
"""

from __future__ import annotations

from typing import Any

PROMPT_TEMPLATE = """### Task
Review the following {language} code{ecosystem_line}. Identify the single most
important finding: its category, severity, confidence, and a one-sentence
summary.

### Code
```
{code}
```

### Finding
"""

TARGET_TEMPLATE = """category: {category}
severity: {severity}
confidence: {confidence}
summary: {summary}
"""


def _ecosystem_line(example: dict[str, Any]) -> str:
    parts = [
        example.get(key)
        for key in ("framework", "library", "database")
        if example.get(key)
    ]
    if not parts:
        return ""
    return f" (using {', '.join(parts)})"


def format_prompt(example: dict[str, Any]) -> str:
    return PROMPT_TEMPLATE.format(
        language=example["language"],
        ecosystem_line=_ecosystem_line(example),
        code=example["code"],
    )


def format_target(example: dict[str, Any]) -> str:
    finding = example["finding"]
    return TARGET_TEMPLATE.format(
        category=finding["category"],
        severity=finding["severity"],
        confidence=finding["confidence"],
        summary=finding["summary"],
    )


def format_example(example: dict[str, Any]) -> tuple[str, str]:
    """Returns (prompt, target). The model is trained to produce target
    given prompt, and is evaluated by parsing its generation for prompt."""
    return format_prompt(example), format_target(example)


def parse_generated_finding(text: str) -> dict[str, str]:
    """Best-effort parse of a `category: ...` / `severity: ...` / ... block
    generated by the model back into a dict, for scoring against the
    expected finding. Unknown or missing fields are simply absent from the
    result rather than raising, since model output is never guaranteed to
    match the template exactly.
    """
    fields: dict[str, str] = {}
    for line in text.splitlines():
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        key = key.strip().lower()
        if key in {"category", "severity", "confidence", "summary"}:
            fields[key] = value.strip()
    return fields
